# Generated by Django 5.0.4 on 2024-04-24 03:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authenticate', '0002_alter_account_primarykey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('primaryKey', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Image', models.ImageField(upload_to='attachments/')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticate.account')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('primaryKey', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Content', models.CharField(default='', max_length=1000)),
                ('UpvotesCount', models.IntegerField(default=0)),
                ('DownVotesCount', models.IntegerField(default=0)),
                ('CommentsCount', models.IntegerField(default=0)),
                ('isEdited', models.BooleanField(default=False)),
                ('Attachments', models.ManyToManyField(blank=True, to='Core.attachments')),
                ('Downvotes', models.ManyToManyField(blank=True, related_name='Downvotes', to='Authenticate.account')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticate.account')),
                ('Upvotes', models.ManyToManyField(blank=True, related_name='Upvotes', to='Authenticate.account')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('primaryKey', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Content', models.CharField(default='', max_length=1000)),
                ('isEdited', models.BooleanField(default=False)),
                ('Attachments', models.ManyToManyField(blank=True, to='Core.attachments')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticate.account')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.post')),
            ],
        ),
    ]
