# Generated by Django 5.0.4 on 2024-04-24 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0002_alter_account_primarykey'),
        ('Core', '0002_post_title_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('primaryKey', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Content', models.CharField(default='', max_length=1000)),
                ('Rating', models.IntegerField(default=0)),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticate.account')),
            ],
        ),
    ]
