# Generated by Django 5.0.4 on 2024-04-24 03:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='primaryKey',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
